In [1]:
import numpy as np
import pandas as pd

# 데이터 불러오기

In [2]:
df = pd.read_csv('../data/ch2_scores_em.csv', index_col='student number')

In [3]:
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [4]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [7]:
scores_df = pd.DataFrame({'score': scores}, index=pd.Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], name = 'student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

# 데이터 중심의 지표

## 평균값(mean)

In [8]:
sum(scores) / len(scores)

55.0

In [9]:
np.mean(scores)

55.0

In [11]:
scores_df.mean()

score    55.0
dtype: float64

### 평균값 오름차순 정렬

In [12]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

## 중앙값(median)
- 오름차순으로 정렬한 후 중앙에 위치하는 값

In [13]:
np.median(scores)

56.5

## 최빈값(mode)
- 가장 많이 나타나는 값

In [15]:
pd.Series([1, 1, 1, 2, 2, 3]).mode()

0    1
dtype: int64

# 데이터의 산포도 지표

## 분산과 표준편차

### 편차(deviation)

In [16]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

### 분산(variance)